fn main() {
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_SECURITY_PROOF");

    let proof_enabled = std::env::var_os("CARGO_FEATURE_SECURITY_PROOF").is_some();
    let (app_manifest, capabilities_path_pattern) = if proof_enabled {
        (
            tauri_build::AppManifest::new().commands(&[
                "proof_install_canary",
                "proof_authorized_probe",
                "proof_lock",
                "proof_status",
            ]),
            "./capabilities/**/*",
        )
    } else {
        // Proof builds generate permissions under `permissions/autogenerated`.
        // Normal builds must not import those proof-only permissions afterwards.
        (
            tauri_build::AppManifest::new().permissions_path_pattern("./permissions/normal/**/*"),
            "./capabilities/default.json",
        )
    };

    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(app_manifest)
            .capabilities_path_pattern(capabilities_path_pattern),
    )
    .expect("failed to run Tauri build script");
}
