fn main() {
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_SECURITY_PROOF");

    let app_manifest = if std::env::var_os("CARGO_FEATURE_SECURITY_PROOF").is_some() {
        tauri_build::AppManifest::new().commands(&[
            "proof_install_canary",
            "proof_authorized_probe",
            "proof_lock",
            "proof_status",
        ])
    } else {
        // Proof builds generate permissions under `permissions/autogenerated`.
        // Normal builds must not import those proof-only permissions afterwards.
        tauri_build::AppManifest::new().permissions_path_pattern("./permissions/normal/**/*")
    };

    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(app_manifest))
        .expect("failed to run Tauri build script");
}
